<?php 
session_start();
?>
<!DOCTYPE html>
<html lang="en-US">

<!-- Mirrored from education-html.themerex.net/video-tutorials.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 03 Mar 2017 03:27:37 GMT -->
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<link href="../content/bootstrap.css" rel="stylesheet" />
<script src="../scripts/jquery-1.9.1.js"></script>
<script src="../scripts/bootstrap.js"></script>

<link rel="icon" type="image/x-icon" href="images/favicon.ico"/>
<title>ASP.NET Tutorials | knowledge.com</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans%3A300italic%2C400italic%2C600italic%2C300%2C400%2C600&amp;subset=latin%2Clatin-ext&amp;ver=4.3.1" type="text/css" media="all"/>
<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:100,100italic,300,300italic,400,400italic,700,700italic&amp;subset=latin,latin-ext,cyrillic,cyrillic-ext" type="text/css" media="all"/>
<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Love+Ya+Like+A+Sister:400&amp;subset=latin" type="text/css" media="all"/>
<link rel="stylesheet" href="css/fontello/css/fontello.css" type="text/css" media="all"/>
<link rel="stylesheet" href="js/rs-plugin/settings.css" type="text/css" media="all"/>
<link rel="stylesheet" href="css/woocommerce/woocommerce-layout.css" type="text/css" media="all"/>
<link rel="stylesheet" href="css/woocommerce/woocommerce-smallscreen.css" type="text/css" media="only screen and (max-width: 768px)"/>
<link rel="stylesheet" href="css/woocommerce/woocommerce.css" type="text/css" media="all"/>
<link rel="stylesheet" href="css/style.css" type="text/css" media="all"/>
<link rel="stylesheet" href="css/shortcodes.css" type="text/css" media="all"/>
<link rel="stylesheet" href="css/core.animation.css" type="text/css" media="all"/>
<link rel="stylesheet" href="css/tribe-style.css" type="text/css" media="all"/>
<link rel="stylesheet" href="css/skins/skin.css" type="text/css" media="all"/>
<link rel="stylesheet" href="css/core.portfolio.css" type="text/css" media="all"/>
<link rel="stylesheet" href="js/mediaelement/mediaelementplayer.min.css" type="text/css" media="all"/>
<link rel="stylesheet" href="js/mediaelement/wp-mediaelement.css" type="text/css" media="all"/>
<link rel="stylesheet" href="js/prettyPhoto/css/prettyPhoto.css" type="text/css" media="all"/>
<link rel="stylesheet" href="js/core.customizer/front.customizer.css" type="text/css" media="all"/>
<link rel="stylesheet" href="js/core.messages/core.messages.css" type="text/css" media="all"/>
<link rel="stylesheet" href="js/swiper/idangerous.swiper.min.css" type="text/css" media="all"/>
<link rel="stylesheet" href="css/custom-style.css" type="text/css" media="all"/>
<link rel="stylesheet" href="css/responsive.css" type="text/css" media="all"/>
<link rel="stylesheet" href="css/skins/skin-responsive.css" type="text/css" media="all"/>
</head>
<body class="page body_style_wide body_filled article_style_boxed template_single-standard top_panel_style_dark top_panel_opacity_solid top_panel_above menu_right sidebar_show sidebar_right">
<a id="toc_top" class="sc_anchor" title="To Top" data-description="&lt;i&gt;Back to top&lt;/i&gt; - &lt;br&gt;scroll to top of the page" data-icon="icon-angle-double-up" data-url="" data-separator="yes"></a>
 
<div class="body_wrap">
<div class="page_wrap">
<div class="top_panel_fixed_wrap"></div>
 
<?php include 'userheader.php'; ?>  
 
<div class="page_content_wrap">
<div class="content_wrap">
 
<div class="content">


<article class="post_item post_item_single page">
<section class="post_content">
<?php 
	$sid=327;
	$obj=new conclass();
	$res=$obj->getdata("select * from subcat_tbl where pk_s_id='$sid'");
		
		while($row=MYSQL_fetch_array($res,MYSQL_ASSOC))
		{
			$sname=$row["s_name"];
			$desc1=$row["s_desc1"];
			$desc2=$row["s_desc2"];
			$desc3=$row["s_desc3"];
		}
?>



<h3 class="widget_title" style="text-align:center"><?php echo $sname;?></h3>
 <strong style="font-size:20px;">
<div class="sc_line sc_line_style_solid margin_top_3em"></div>
<h4>What is Caching?</h4>
<p>Caching is a technique of storing frequently used data/information in memory, so that, when the same data/information is needed next time, it could be directly retrieved from the memory instead of being generated by the application.</p>
<p>Caching is extremely important for performance boosting in ASP.NET, as the pages and controls are dynamically generated here. It is especially important for data related transactions, as these are expensive in terms of response time.</p>
<p>Caching places frequently used data in quickly accessed media such as the random access memory of the computer. The ASP.NET runtime includes a key-value map of CLR objects called cache. This resides with the application and is available via the HttpContext and System.Web.UI.Page.</p>
<p>In some respect, caching is similar to storing the state objects. However, the storing information in state objects is deterministic, i.e., you can count on the data being stored there, and caching of data is nondeterministic.</p>
<p>The data will not be available in the following cases:</p>
<ul class="list">
<li>If its lifetime expires,</li>
<li>If the application releases its memory,</li>
<li>If caching does not take place for some reason.</li>
</ul>
<p>You can access items in the cache using an indexer and may control the lifetime of objects in the cache and set up links between the cached objects and their physical sources.</p>
<h4>Caching in ASP.Net</h4>
<p>ASP.NET provides the following different types of caching:</p>
<ul class="list">
<li><p><b>Output Caching</b> : Output cache stores a copy of the finally rendered HTML pages or part of pages sent to the client. When the next client requests for this page, instead of regenerating the page, a cached copy of the page is sent, thus saving time.</p></li> 
<li><p><b>Data Caching</b> : Data caching means caching data from a data source. As long as the cache is not expired, a request for the data will be fulfilled from the cache. When the cache is expired, fresh data is obtained by the data source and the cache is refilled.</p></li> 
<li><p><b>Object Caching</b> : Object caching is caching the objects on a page, such as data-bound controls. The cached data is stored in server memory.</p></li> 
<li><p><b>Class Caching</b> : Web pages or web services are compiled into a page class in the assembly, when run for the first time. Then the assembly is cached in the server. Next time when a request is made for the page or service, the cached assembly is referred to. When the source code is changed, the CLR recompiles the assembly.</p></li> 
<li><p><b>Configuration Caching</b> : Application wide configuration information is stored in a configuration file. Configuration caching stores the configuration information in the server memory.</p></li>
</ul>
<p>In this tutorial, we will consider output caching, data caching, and object caching.</p>
<h4>Output Caching</h4>
<p>Rendering a page may involve some complex processes such as, database access, rendering complex controls etc. Output caching allows bypassing the round trips to server by caching data in memory. Even the whole page could be cached. </p>
<p>The OutputCache directive is responsible of output caching. It enables output caching and provides certain control over its behaviour.</p>
<p>Syntax for OutputCache directive:</p>
<pre class="prettyprint notranslate prettyprinted"><span class="pun">&lt;%@</span><span class="pln"> </span><span class="typ">OutputCache</span><span class="pln"> </span><span class="typ">Duration</span><span class="pun">=</span><span class="str">"15"</span><span class="pln"> </span><span class="typ">VaryByParam</span><span class="pun">=</span><span class="str">"None"</span><span class="pln"> %&gt;</span></pre>
<p>Put this directive under the page directive. This tells the environment to cache the page for 15 seconds. The following event handler for page load would help in testing that the page was really cached.</p>
<pre class="prettyprint notranslate prettyprinted"><span class="kwd">protected</span><span class="pln"> </span><span class="kwd">void</span><span class="pln"> </span><span class="typ">Page_Load</span><span class="pun">(</span><span class="kwd">object</span><span class="pln"> sender</span><span class="pun">,</span><span class="pln"> </span><span class="typ">EventArgs</span><span class="pln"> e</span><span class="pun">)</span><span class="pln">
</span><span class="pun">{</span><span class="pln">
   </span><span class="typ">Thread</span><span class="pun">.</span><span class="typ">Sleep</span><span class="pun">(</span><span class="lit">10000</span><span class="pun">);</span><span class="pln">  
   </span><span class="typ">Response</span><span class="pun">.</span><span class="typ">Write</span><span class="pun">(</span><span class="str">"This page was generated and cache at:"</span><span class="pln"> </span><span class="pun">+</span><span class="pln">
   </span><span class="typ">DateTime</span><span class="pun">.</span><span class="typ">Now</span><span class="pun">.</span><span class="typ">ToString</span><span class="pun">());</span><span class="pln">
</span><span class="pun">}</span></pre>
<p>The <b>Thread.Sleep()</b> method stops the process thread for the specified time. In this example, the thread is stopped for 10 seconds, so when the page is loaded for first time, it takes 10 seconds. However, next time you refresh the page it does not take any time, as the page is retrieved from the cache without being loaded.</p>
<p>The OutputCache directive has the following attributes, which helps in controlling the behaviour of the output cache:</p>
<table class="table table-bordered">
<tbody><tr>
<th style="width:30%">Attribute</th>
<th style="width:30%">Values</th>
<th>Description</th>
</tr>
<tr>
<td>DiskCacheable</td>
<td>true/false</td>
<td>Specifies that output could be written to a disk based cache.</td>
</tr>
<tr>
<td>NoStore</td>
<td>true/false</td>
<td>Specifies that the "no store" cache control header is sent or not.</td>
</tr>
<tr>
<td>CacheProfile</td>
<td>String name</td>
<td>Name of a cache profile as to be stored in web.config.</td>
</tr>
<tr>
<td>VaryByParam</td>
<td>
<p>None</p>
<p>*</p>Param- name</td>
<td>Semicolon delimited list of string specifies query string values in a GET request or variable in a POST request.</td>
</tr>
<tr>
<td>VaryByHeader</td>
<td>
<p>*</p>
<p>Header names</p>
</td>
<td>Semicolon delimited list of strings specifies headers that might be submitted by a client.</td>
</tr>
<tr>
<td>VaryByCustom</td>
<td>
<p>Browser</p>
<p>Custom string</p>
</td>
<td>Tells ASP.NET to vary the output cache by browser name and version or by a custom string.</td>
</tr>
<tr>
<td>Location</td>
<td>
<p>Any</p>
<p>Client</p>
<p>Downstream</p>
<p>Server</p>
<p>None</p>
</td>
<td>
<p>Any: page may be cached anywhere.</p>
<p>Client: cached content remains at browser.</p>
<p>Downstream: cached content stored in downstream and server both.</p>
<p>Server: cached content saved only on server.</p>
<p>None: disables caching.</p>
</td>
</tr>
<tr>
<td>Duration</td>
<td>Number</td>
<td>Number of seconds the page or control is cached.</td>
</tr>
</tbody></table>
<p>Let us add a text box and a button to the previous example and add this event handler for the button.</p>
<pre class="prettyprint notranslate prettyprinted"><span class="kwd">protected</span><span class="pln"> </span><span class="kwd">void</span><span class="pln"> btnmagic_Click</span><span class="pun">(</span><span class="kwd">object</span><span class="pln"> sender</span><span class="pun">,</span><span class="pln"> </span><span class="typ">EventArgs</span><span class="pln"> e</span><span class="pun">)</span><span class="pln">
</span><span class="pun">{</span><span class="pln">
   </span><span class="typ">Response</span><span class="pun">.</span><span class="typ">Write</span><span class="pun">(</span><span class="str">"&lt;br&gt;&lt;br&gt;"</span><span class="pun">);</span><span class="pln">
   </span><span class="typ">Response</span><span class="pun">.</span><span class="typ">Write</span><span class="pun">(</span><span class="str">"&lt;h4&gt; Hello, "</span><span class="pln"> </span><span class="pun">+</span><span class="pln"> </span><span class="kwd">this</span><span class="pun">.</span><span class="pln">txtname</span><span class="pun">.</span><span class="typ">Text</span><span class="pln"> </span><span class="pun">+</span><span class="pln"> </span><span class="str">"&lt;/h4&gt;"</span><span class="pun">);</span><span class="pln">
</span><span class="pun">}</span></pre>
<p>Change the OutputCache directive:</p>
<pre class="prettyprint notranslate prettyprinted"><span class="pun">&lt;%@</span><span class="pln"> </span><span class="typ">OutputCache</span><span class="pln"> </span><span class="typ">Duration</span><span class="pun">=</span><span class="str">"60"</span><span class="pln"> </span><span class="typ">VaryByParam</span><span class="pun">=</span><span class="str">"txtname"</span><span class="pln"> %&gt;</span></pre>
<p>When the program is executed, ASP.NET caches the page on the basis of the name in the text box.</p>
<h4>Data Caching</h4>
<p>The main aspect of data caching is caching the data source controls. We have already discussed that the data source controls represent data in a data source, like a database or an XML file. These controls derive from the abstract class DataSourceControl and have the following inherited properties for implementing caching:</p>
<ul class="list">
<li><p><b>CacheDuration</b> - It sets the number of seconds for which the data source will cache data.</p></li> 
<li><p><b>CacheExpirationPolicy</b> - It defines the cache behavior when the data in cache has expired.</p></li> 
<li><p><b>CacheKeyDependency</b> - It identifies a key for the controls that auto-expires the content of its cache when removed.</p></li> 
<li><p><b>EnableCaching</b> - It specifies whether or not to cache the data.</p></li> 
</ul>
<h5>Example</h5>
<p>To demonstrate data caching, create a new website and add a new web form on it. Add a SqlDataSource control with the database connection already used in the data access tutorials.</p>
<p>For this example, add a label to the page, which would show the response time for the page.</p>
<pre class="prettyprint notranslate prettyprinted"><span class="tag">&lt;asp:Label</span><span class="pln"> </span><span class="atn">ID</span><span class="pun">=</span><span class="atv">"lbltime"</span><span class="pln"> </span><span class="atn">runat</span><span class="pun">=</span><span class="atv">"server"</span><span class="tag">&gt;&lt;/asp:Label&gt;</span></pre>
<p>Apart from the label, the content page is same as in the data access tutorial. Add an event handler for the page load event:</p>
<pre class="prettyprint notranslate prettyprinted"><span class="kwd">protected</span><span class="pln"> </span><span class="kwd">void</span><span class="pln"> </span><span class="typ">Page_Load</span><span class="pun">(</span><span class="kwd">object</span><span class="pln"> sender</span><span class="pun">,</span><span class="pln"> </span><span class="typ">EventArgs</span><span class="pln"> e</span><span class="pun">)</span><span class="pln">
</span><span class="pun">{</span><span class="pln">
   lbltime</span><span class="pun">.</span><span class="typ">Text</span><span class="pln"> </span><span class="pun">=</span><span class="pln"> </span><span class="typ">String</span><span class="pun">.</span><span class="typ">Format</span><span class="pun">(</span><span class="str">"Page posted at: {0}"</span><span class="pun">,</span><span class="pln"> </span><span class="typ">DateTime</span><span class="pun">.</span><span class="typ">Now</span><span class="pun">.</span><span class="typ">ToLongTimeString</span><span class="pun">());</span><span class="pln">
</span><span class="pun">}</span></pre>
<p>The designed pag/asp.net/images/data_caching.jpg" alt="Data Caching">
<p>When you execute the page for the first time, nothing different happens, the label shows that, each time you refresh the page, the page is reloaded and the time shown on the label changes.</p>
<p>Next, set the EnableCaching attribute of the data source control to be 'true' and set the Cacheduration attribute to '60'. It will implement caching and the cache will expire every 60 seconds.</p>
<p>The timestamp changes with every refresh, but if you change the data in the table within these 60 seconds, it is not shown before the cache expires.</p>
<pre class="prettyprint notranslate prettyprinted"><span class="pln">&lt;asp:SqlDataSource ID = "SqlDataSource1" runat = "server" 
   ConnectionString = "</span><span class="pun">&lt;%</span><span class="pln">$ </span><span class="typ">ConnectionStrings</span><span class="pun">:</span><span class="pln"> </span><span class="typ">ASPDotNetStepByStepConnectionString</span><span class="pln"> %&gt;" 
   ProviderName = "</span><span class="pun">&lt;%</span><span class="pln">$ </span><span class="typ">ConnectionStrings</span><span class="pun">:</span><span class="pln"> </span><span class="typ">ASPDotNetStepByStepConnectionString</span><span class="pun">.</span><span class="typ">ProviderName</span><span class="pln"> %&gt;" 
   SelectCommand = "SELECT * FROM [DotNetReferences]"
   EnableCaching = "true" CacheDuration = "60"&gt;         
</span><span class="tag">&lt;/asp:SqlDataSource&gt;</span></pre>
<h4>Object Caching</h4>
<p>Object caching provides more flexibility than other cache techniques. You can use object caching to place any object in the cache. The object can be of any type - a data type, a web control, a class, a dataset object, etc.  The item is added to the cache simply by assigning a new key name, shown as follows Like:</p>
<pre class="prettyprint notranslate prettyprinted"><span class="typ">Cache</span><span class="pun">[</span><span class="str">"key"</span><span class="pun">]</span><span class="pln"> </span><span class="pun">=</span><span class="pln"> item</span><span class="pun">;</span></pre>
<p>ASP.NET also provides the Insert() method for inserting an object to the cache. This method has four overloaded versions. Let us see them:</p>
<table class="table table-bordered">
<tbody><tr>
<th style="width:30%">Overload</th>
<th>Description</th>
</tr>
<tr>
<td>Cache.Insert((key, value);</td>
<td>Inserts an item into the cache with the key name and value with default priority and expiration.</td>
</tr>
<tr>
<td>Cache.Insert(key, value, dependencies);</td>
<td>Inserts an item into the cache with key, value, default priority, expiration and a CacheDependency name that links to other files or items so that when these change the cache item remains no longer valid.</td>
</tr>
<tr>
<td>Cache.Insert(key, value, dependencies, absoluteExpiration, slidingExpiration);</td>
<td>This indicates an expiration policy along with the above issues.</td>
</tr>
<tr>
<td>Cache.Insert(key, value, dependencies, absoluteExpiration, slidingExpiration, priority, onRemoveCallback);</td>
<td>This along with the parameters also allows you to set a priority for the cache item and a delegate that, points to a method to be invoked when the item is removed.</td>
</tr>
</tbody></table>
<p>Sliding expiration is used to remove an item from the cache when it is not used for the specified time span. The following code snippet stores an item with a sliding expiration of 10 minutes with no dependencies.</p>
<pre class="prettyprint notranslate prettyprinted"><span class="typ">Cache</span><span class="pun">.</span><span class="typ">Insert</span><span class="pun">(</span><span class="str">"my_item"</span><span class="pun">,</span><span class="pln"> obj</span><span class="pun">,</span><span class="pln"> </span><span class="kwd">null</span><span class="pun">,</span><span class="pln"> </span><span class="typ">DateTime</span><span class="pun">.</span><span class="typ">MaxValue</span><span class="pun">,</span><span class="pln"> </span><span class="typ">TimeSpan</span><span class="pun">.</span><span class="typ">FromMinutes</span><span class="pun">(</span><span class="lit">10</span><span class="pun">));</span></pre>
<h5>Example</h5>
<p>Create a page with just a button and a label. Write the following code in the page load event:</p>
<pre class="prettyprint notranslate prettyprinted"><span class="kwd">protected</span><span class="pln"> </span><span class="kwd">void</span><span class="pln"> </span><span class="typ">Page_Load</span><span class="pun">(</span><span class="kwd">object</span><span class="pln"> sender</span><span class="pun">,</span><span class="pln"> </span><span class="typ">EventArgs</span><span class="pln"> e</span><span class="pun">)</span><span class="pln">
</span><span class="pun">{</span><span class="pln">
   </span><span class="kwd">if</span><span class="pln"> </span><span class="pun">(</span><span class="kwd">this</span><span class="pun">.</span><span class="typ">IsPostBack</span><span class="pun">)</span><span class="pln">
   </span><span class="pun">{</span><span class="pln">
      lblinfo</span><span class="pun">.</span><span class="typ">Text</span><span class="pln"> </span><span class="pun">+=</span><span class="pln"> </span><span class="str">"Page Posted Back.&lt;br/&gt;"</span><span class="pun">;</span><span class="pln">
   </span><span class="pun">}</span><span class="pln">
   </span><span class="kwd">else</span><span class="pln">
   </span><span class="pun">{</span><span class="pln">
      lblinfo</span><span class="pun">.</span><span class="typ">Text</span><span class="pln"> </span><span class="pun">+=</span><span class="pln"> </span><span class="str">"page Created.&lt;br/&gt;"</span><span class="pun">;</span><span class="pln">
   </span><span class="pun">}</span><span class="pln">
   
   </span><span class="kwd">if</span><span class="pln"> </span><span class="pun">(</span><span class="typ">Cache</span><span class="pun">[</span><span class="str">"testitem"</span><span class="pun">]</span><span class="pln"> </span><span class="pun">==</span><span class="pln"> </span><span class="kwd">null</span><span class="pun">)</span><span class="pln">
   </span><span class="pun">{</span><span class="pln">
      lblinfo</span><span class="pun">.</span><span class="typ">Text</span><span class="pln"> </span><span class="pun">+=</span><span class="pln"> </span><span class="str">"Creating test item.&lt;br/&gt;"</span><span class="pun">;</span><span class="pln">
      </span><span class="typ">DateTime</span><span class="pln"> testItem </span><span class="pun">=</span><span class="pln"> </span><span class="typ">DateTime</span><span class="pun">.</span><span class="typ">Now</span><span class="pun">;</span><span class="pln">
      lblinfo</span><span class="pun">.</span><span class="typ">Text</span><span class="pln"> </span><span class="pun">+=</span><span class="pln"> </span><span class="str">"Storing test item in cache "</span><span class="pun">;</span><span class="pln">
      lblinfo</span><span class="pun">.</span><span class="typ">Text</span><span class="pln"> </span><span class="pun">+=</span><span class="pln"> </span><span class="str">"for 30 seconds.&lt;br/&gt;"</span><span class="pun">;</span><span class="pln">
      </span><span class="typ">Cache</span><span class="pun">.</span><span class="typ">Insert</span><span class="pun">(</span><span class="str">"testitem"</span><span class="pun">,</span><span class="pln"> testItem</span><span class="pun">,</span><span class="pln"> </span><span class="kwd">null</span><span class="pun">,</span><span class="pln"> 
      </span><span class="typ">DateTime</span><span class="pun">.</span><span class="typ">Now</span><span class="pun">.</span><span class="typ">AddSeconds</span><span class="pun">(</span><span class="lit">30</span><span class="pun">),</span><span class="pln"> </span><span class="typ">TimeSpan</span><span class="pun">.</span><span class="typ">Zero</span><span class="pun">);</span><span class="pln">
   </span><span class="pun">}</span><span class="pln">
   </span><span class="kwd">else</span><span class="pln">
   </span><span class="pun">{</span><span class="pln">
      lblinfo</span><span class="pun">.</span><span class="typ">Text</span><span class="pln"> </span><span class="pun">+=</span><span class="pln"> </span><span class="str">"Retrieving test item.&lt;br/&gt;"</span><span class="pun">;</span><span class="pln">
      </span><span class="typ">DateTime</span><span class="pln"> testItem </span><span class="pun">=</span><span class="pln"> </span><span class="pun">(</span><span class="typ">DateTime</span><span class="pun">)</span><span class="typ">Cache</span><span class="pun">[</span><span class="str">"testitem"</span><span class="pun">];</span><span class="pln">
      lblinfo</span><span class="pun">.</span><span class="typ">Text</span><span class="pln"> </span><span class="pun">+=</span><span class="pln"> </span><span class="str">"Test item is: "</span><span class="pln"> </span><span class="pun">+</span><span class="pln"> testItem</span><span class="pun">.</span><span class="typ">ToString</span><span class="pun">();</span><span class="pln">
      lblinfo</span><span class="pun">.</span><span class="typ">Text</span><span class="pln"> </span><span class="pun">+=</span><span class="pln"> </span><span class="str">"&lt;br/&gt;"</span><span class="pun">;</span><span class="pln">
   </span><span class="pun">}</span><span class="pln">
      
   lblinfo</span><span class="pun">.</span><span class="typ">Text</span><span class="pln"> </span><span class="pun">+=</span><span class="pln"> </span><span class="str">"&lt;br/&gt;"</span><span class="pun">;</span><span class="pln">
</span><span class="pun">}</span></pre>
<p>When the page is loaded for the first time, it says:</p>
<pre class="result notranslate">Page Created.
Creating test item.
Storing test item in cache for 30 seconds.
</pre>
<p>If you click on the button again within 30 seconds, the page is posted back but the label control gets its information from the cache as shown:</p>
<pre class="result notranslate">Page Posted Back.
Retrieving test item.
Test item is: 14-07-2010 01:25:04
</pre>





<div class="sc_line sc_line_style_solid margin_top_3em"></div>

<div class="row">
<a href="326_data.php"> <button class="sc_button sc_button_square sc_button_style_filled sc_button_bg_link sc_button_size_small alignleft sc_buttons_st1 sc_buttons_st5">Previous</button></a>

<div style="padding-right:50px">

<a href="328_data.php"> <button class="sc_button sc_button_square sc_button_style_filled sc_button_bg_link sc_button_size_small alignright sc_buttons_st1 sc_buttons_st5">NEXT</button></a>
</div>
 </div>
 
 
</section>
</article>



 

</div>
 
 
<div class="sidebar widget_area bg_tint_light sidebar_style_light">
 
<aside class="widget">

<?php include 'aspnet_header.php'; ?></aside>
 
  
</div>
 
</div>
</div>
 
 

<?php include 'userfooter.php'; ?>  
 
 
</div>
</div>
 
<a href="#" class="scroll_to_top icon-up-2" title="Scroll to top"></a>
<div class="custom_html_section"></div>
<script type="text/javascript" src="js/jquery/jquery.min.js"></script>
<script type="text/javascript" src="js/jquery/jquery-migrate.min.js"></script>
<script type="text/javascript" src="js/jquery/ui/core.min.js"></script>
<script type="text/javascript" src="js/jquery/ui/widget.min.js"></script>
<script type="text/javascript" src="js/jquery/ui/tabs.min.js"></script>
<script type="text/javascript" src="js/jquery/ui/accordion.min.js"></script>
<script type="text/javascript" src="js/jquery/ui/effect.min.js"></script>
<script type="text/javascript" src="js/jquery/ui/effect-fade.min.js"></script>
<script type="text/javascript" src="js/jquery/jquery.blockUI.min.js"></script>
<script type="text/javascript" src="js/jquery/jquery.cookie.min.js"></script>
<script type="text/javascript" src="js/global.min.js"></script>
<script type="text/javascript" src="js/core.utils.min.js"></script>
<script type="text/javascript" src="js/core.init.min.js"></script>
<script type="text/javascript" src="js/shortcodes/shortcodes.min.js"></script>
<script type="text/javascript" src="js/superfish.min.js"></script>
<script type="text/javascript" src="js/jquery.slidemenu.min.js"></script>
<script type="text/javascript" src="js/mediaelement/mediaelement-and-player.min.js"></script>
<script type="text/javascript" src="js/mediaelement/wp-mediaelement.min.js"></script>
<script type="text/javascript" src="js/core.messages/core.messages.min.js"></script>
<script type="text/javascript" src="js/swiper/idangerous.swiper-2.7.min.js"></script>
<script type="text/javascript" src="js/swiper/idangerous.swiper.scrollbar-2.4.min.js"></script>
<script type="text/javascript" src="js/prettyPhoto/jquery.prettyPhoto.min.js"></script>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript" src="js/core.googlemap.min.js"></script>
<script type="text/javascript" src="js/diagram/chart.min.js"></script>
<script type="text/javascript" src="js/core.customizer/front.customizer.min.js"></script>
<script type="text/javascript" src="js/skin.customizer.min.js"></script>
</body>

<!-- Mirrored from education-html.themerex.net/shortcodes.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 03 Mar 2017 03:27:37 GMT -->
</html>